// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: credit_card.proto

package data

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Timestamp struct {
	Timestamp            *types.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3303e5a2b31807, []int{0}
}
func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetTimestamp() *types.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type BandiUser struct {
	// @inject_tag: gorm:"primary_key"
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty" gorm:"primary_key"`
	// @inject_tag: gorm:"foreignkey:UserName;association_foreignkey:Username"
	CreditCards          []*BandiCreditCard `protobuf:"bytes,2,rep,name=CreditCards,proto3" json:"CreditCards,omitempty" gorm:"foreignkey:UserName;association_foreignkey:Username"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BandiUser) Reset()         { *m = BandiUser{} }
func (m *BandiUser) String() string { return proto.CompactTextString(m) }
func (*BandiUser) ProtoMessage()    {}
func (*BandiUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3303e5a2b31807, []int{1}
}
func (m *BandiUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BandiUser.Unmarshal(m, b)
}
func (m *BandiUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BandiUser.Marshal(b, m, deterministic)
}
func (m *BandiUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BandiUser.Merge(m, src)
}
func (m *BandiUser) XXX_Size() int {
	return xxx_messageInfo_BandiUser.Size(m)
}
func (m *BandiUser) XXX_DiscardUnknown() {
	xxx_messageInfo_BandiUser.DiscardUnknown(m)
}

var xxx_messageInfo_BandiUser proto.InternalMessageInfo

func (m *BandiUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *BandiUser) GetCreditCards() []*BandiCreditCard {
	if m != nil {
		return m.CreditCards
	}
	return nil
}

// Contains Composite Primary Key and Foreign Key
// User Details "belongs to" an User
type BandiUserDetails struct {
	// @inject_tag: gorm:"primary_key"
	Firstname string `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty" gorm:"primary_key"`
	// @inject_tag: gorm:"primary_key"
	Lastname string `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty" gorm:"primary_key"`
	// @inject_tag: gorm:"foreignkey:ForeignKeyUserName;association_foreignkey:Username"
	User                 *BandiUser `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty" gorm:"foreignkey:ForeignKeyUserName;association_foreignkey:Username"`
	ForeignKeyUserName   string     `protobuf:"bytes,4,opt,name=foreignKeyUserName,proto3" json:"foreignKeyUserName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BandiUserDetails) Reset()         { *m = BandiUserDetails{} }
func (m *BandiUserDetails) String() string { return proto.CompactTextString(m) }
func (*BandiUserDetails) ProtoMessage()    {}
func (*BandiUserDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3303e5a2b31807, []int{2}
}
func (m *BandiUserDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BandiUserDetails.Unmarshal(m, b)
}
func (m *BandiUserDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BandiUserDetails.Marshal(b, m, deterministic)
}
func (m *BandiUserDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BandiUserDetails.Merge(m, src)
}
func (m *BandiUserDetails) XXX_Size() int {
	return xxx_messageInfo_BandiUserDetails.Size(m)
}
func (m *BandiUserDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_BandiUserDetails.DiscardUnknown(m)
}

var xxx_messageInfo_BandiUserDetails proto.InternalMessageInfo

func (m *BandiUserDetails) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *BandiUserDetails) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *BandiUserDetails) GetUser() *BandiUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *BandiUserDetails) GetForeignKeyUserName() string {
	if m != nil {
		return m.ForeignKeyUserName
	}
	return ""
}

type BandiCreditCard struct {
	// @inject_tag: gorm:"unique;not null;size:16;unique_index"
	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty" gorm:"unique;not null;size:16;unique_index"`
	// @inject_tag: gorm:"not null" bandi:"only4digits"
	Cvv int32 `protobuf:"varint,2,opt,name=cvv,proto3" json:"cvv,omitempty" gorm:"not null" bandi:"only4digits"`
	// @inject_tag: gorm:"type:timestamp;index:expiry;not null;"
	Expiry *Timestamp `protobuf:"bytes,3,opt,name=expiry,proto3" json:"expiry,omitempty" gorm:"type:timestamp;index:expiry;not null;"`
	// @inject_tag: gorm:"-"
	IgnoreME string `protobuf:"bytes,4,opt,name=ignoreME,proto3" json:"ignoreME,omitempty" gorm:"-"`
	UserName string `protobuf:"bytes,5,opt,name=userName,proto3" json:"userName,omitempty"`
	// @inject_tag: gorm:"primary_key"
	ID                   string   `protobuf:"bytes,6,opt,name=ID,proto3" json:"ID,omitempty" gorm:"primary_key"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BandiCreditCard) Reset()         { *m = BandiCreditCard{} }
func (m *BandiCreditCard) String() string { return proto.CompactTextString(m) }
func (*BandiCreditCard) ProtoMessage()    {}
func (*BandiCreditCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3303e5a2b31807, []int{3}
}
func (m *BandiCreditCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BandiCreditCard.Unmarshal(m, b)
}
func (m *BandiCreditCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BandiCreditCard.Marshal(b, m, deterministic)
}
func (m *BandiCreditCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BandiCreditCard.Merge(m, src)
}
func (m *BandiCreditCard) XXX_Size() int {
	return xxx_messageInfo_BandiCreditCard.Size(m)
}
func (m *BandiCreditCard) XXX_DiscardUnknown() {
	xxx_messageInfo_BandiCreditCard.DiscardUnknown(m)
}

var xxx_messageInfo_BandiCreditCard proto.InternalMessageInfo

func (m *BandiCreditCard) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *BandiCreditCard) GetCvv() int32 {
	if m != nil {
		return m.Cvv
	}
	return 0
}

func (m *BandiCreditCard) GetExpiry() *Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

func (m *BandiCreditCard) GetIgnoreME() string {
	if m != nil {
		return m.IgnoreME
	}
	return ""
}

func (m *BandiCreditCard) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *BandiCreditCard) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "data.Timestamp")
	golang_proto.RegisterType((*Timestamp)(nil), "data.Timestamp")
	proto.RegisterType((*BandiUser)(nil), "data.BandiUser")
	golang_proto.RegisterType((*BandiUser)(nil), "data.BandiUser")
	proto.RegisterType((*BandiUserDetails)(nil), "data.BandiUserDetails")
	golang_proto.RegisterType((*BandiUserDetails)(nil), "data.BandiUserDetails")
	proto.RegisterType((*BandiCreditCard)(nil), "data.BandiCreditCard")
	golang_proto.RegisterType((*BandiCreditCard)(nil), "data.BandiCreditCard")
}

func init() { proto.RegisterFile("credit_card.proto", fileDescriptor_dc3303e5a2b31807) }
func init() { golang_proto.RegisterFile("credit_card.proto", fileDescriptor_dc3303e5a2b31807) }

var fileDescriptor_dc3303e5a2b31807 = []byte{
	// 506 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0x55, 0x7f, 0x56, 0xad, 0xee, 0xc5, 0xc0, 0x82, 0xa9, 0xaa, 0xf8, 0xb1, 0x3a, 0x01, 0x23,
	0xda, 0x12, 0x29, 0x08, 0x81, 0xc4, 0x55, 0xb2, 0x0c, 0x29, 0x42, 0x54, 0x10, 0x95, 0x6b, 0x70,
	0x9b, 0xaf, 0x99, 0x45, 0x6a, 0x17, 0xdb, 0x59, 0xd9, 0x03, 0xf0, 0x02, 0x79, 0x03, 0xde, 0x84,
	0x77, 0xe1, 0x45, 0x90, 0x9d, 0x9f, 0x76, 0x08, 0xee, 0xfc, 0x9d, 0x73, 0x7c, 0x7c, 0x8e, 0x6d,
	0x74, 0x77, 0x29, 0x21, 0x65, 0xfa, 0xf3, 0x92, 0xca, 0xd4, 0xdd, 0x48, 0xa1, 0x05, 0xee, 0xa7,
	0x54, 0xd3, 0xc9, 0x99, 0x1d, 0x96, 0xe7, 0x19, 0xf0, 0x73, 0xb5, 0xa5, 0x59, 0x06, 0xd2, 0x13,
	0x1b, 0xcd, 0x04, 0x57, 0x1e, 0xe5, 0x5c, 0x68, 0x6a, 0xd7, 0xd5, 0x9e, 0xc9, 0xbd, 0x4c, 0x64,
	0xc2, 0x2e, 0x3d, 0xb3, 0xaa, 0xd1, 0xc7, 0x99, 0x10, 0x59, 0x0e, 0x9e, 0x9d, 0x16, 0xc5, 0xca,
	0xd3, 0x6c, 0x0d, 0x4a, 0xd3, 0xf5, 0xa6, 0x12, 0x4c, 0x2f, 0xd1, 0x70, 0xde, 0x40, 0xf8, 0x35,
	0x1a, 0xb6, 0xfc, 0xb8, 0x43, 0x3a, 0xa7, 0x23, 0x7f, 0xe2, 0x56, 0x0e, 0x6e, 0xe3, 0xe0, 0xb6,
	0xf2, 0x64, 0x27, 0x9e, 0x7e, 0x41, 0xc3, 0x90, 0xf2, 0x94, 0x7d, 0x52, 0x20, 0xf1, 0x04, 0x1d,
	0x16, 0x0a, 0x24, 0xa7, 0x6b, 0xb0, 0x2e, 0xc3, 0xa4, 0x9d, 0xf1, 0x2b, 0x34, 0xba, 0xb0, 0x7d,
	0x2f, 0xa8, 0x4c, 0xd5, 0xb8, 0x4b, 0x7a, 0xa7, 0x23, 0xff, 0xbe, 0x6b, 0x0a, 0xbb, 0xd6, 0x61,
	0xc7, 0x26, 0xfb, 0xca, 0xe9, 0xcf, 0x0e, 0xba, 0xd3, 0x1e, 0x11, 0x81, 0xa6, 0x2c, 0x57, 0xf8,
	0x01, 0x1a, 0xae, 0x98, 0x54, 0x7a, 0xef, 0xa8, 0x1d, 0x60, 0x72, 0xe4, 0xb4, 0x26, 0xbb, 0x55,
	0x8e, 0x66, 0xc6, 0x27, 0xa8, 0x6f, 0x32, 0x8d, 0x7b, 0xb6, 0xe5, 0xd1, 0x5e, 0x00, 0xe3, 0x9f,
	0x58, 0x12, 0xbb, 0x08, 0xaf, 0x84, 0x04, 0x96, 0xf1, 0x77, 0x70, 0x63, 0xf0, 0x99, 0xb1, 0xea,
	0x5b, 0xab, 0x7f, 0x30, 0xd3, 0x1f, 0x3d, 0x74, 0xf4, 0x57, 0x09, 0xfc, 0x06, 0x0d, 0x78, 0xb1,
	0x5e, 0x80, 0xac, 0xf2, 0x85, 0x27, 0x65, 0x40, 0x9c, 0xc1, 0xcc, 0x42, 0xfe, 0xf1, 0xfc, 0x0a,
	0x48, 0x25, 0x26, 0x46, 0x4d, 0x2a, 0x3c, 0xa9, 0xb7, 0x60, 0x1f, 0xf5, 0x96, 0xd7, 0xd7, 0x36,
	0xfc, 0x41, 0x48, 0xca, 0xe0, 0xa1, 0x63, 0x66, 0xff, 0xf8, 0x03, 0x55, 0x6a, 0x2b, 0x64, 0x4a,
	0x56, 0x42, 0x12, 0x7d, 0xc5, 0x14, 0xb1, 0xa9, 0x0d, 0x89, 0x67, 0x68, 0x00, 0xdf, 0x37, 0x4c,
	0xde, 0xdc, 0xee, 0xd6, 0x3e, 0x5b, 0xf8, 0xa4, 0x0c, 0xa6, 0xce, 0x61, 0x63, 0xf1, 0x5f, 0xb3,
	0xda, 0x05, 0x7f, 0x44, 0x87, 0x2c, 0xe3, 0x42, 0xc2, 0xfb, 0xcb, 0xaa, 0x7a, 0xf8, 0xb2, 0x0c,
	0x7c, 0xa7, 0x05, 0xfd, 0xa7, 0x73, 0x50, 0x9a, 0xc4, 0x5c, 0x9b, 0x27, 0xce, 0xc9, 0x5b, 0x06,
	0x79, 0x7a, 0x46, 0x22, 0xc1, 0x9f, 0x69, 0xa2, 0xb4, 0x90, 0x40, 0x18, 0x27, 0x51, 0x98, 0xb4,
	0x3b, 0x9a, 0x0f, 0x62, 0x6f, 0xf3, 0x60, 0xf7, 0x41, 0xcc, 0x8c, 0x43, 0xd4, 0x8d, 0xa3, 0xf1,
	0xc0, 0x1e, 0xe4, 0x97, 0x81, 0xe7, 0x74, 0xe3, 0xc8, 0x7f, 0x1e, 0x90, 0x82, 0xb3, 0x6f, 0x05,
	0x90, 0x38, 0xf2, 0x12, 0xb1, 0x25, 0x73, 0xf1, 0x15, 0x78, 0x1d, 0xf8, 0xd6, 0x0d, 0x26, 0xdd,
	0x38, 0x0a, 0xfb, 0xbf, 0x7e, 0x3f, 0xea, 0x2c, 0x06, 0xf6, 0xcb, 0xbe, 0xf8, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x79, 0x2a, 0x6c, 0x75, 0x61, 0x03, 0x00, 0x00,
}
